centos_project_id                      = "dev-csye-6225-webapp-1" // centos_project_id = "csye-6225-test-1"
centos_source_image_family             = "centos-stream-8"
centos_zone                            = "us-east1-b"
centos_disable_default_service_account = "false"
centos_region                          = "us-east1"
centos_machine_type                    = "e2-standard-4" // centos_machine_type = "e2-micro"
centos_image_name                      = "webapp-image"
centos_ssh_username                    = "centos-ssh"
webapp_node_env                        = "production"
webapp_port                            = 3000
webapp_db_host                         = "localhost"
webapp_db_port                         = 3306
webapp_db_username                     = "root"
webapp_db_password                     = ""
webapp_db_name                         = "healthz_db_dev"
webapp_db_host_test                    = "localhost"
webapp_db_port_test                    = 3306
webapp_db_username_test                = "root"
webapp_db_password_test                = ""
webapp_db_name_test                    = "healthz_db_test"
webapp_db_host_prod                    = "localhost"
webapp_db_port_prod                    = 3306
webapp_db_username_prod                = "root"
webapp_db_password_prod                = ""
webapp_db_name_prod                    = "healthz_db_prod"