name: Node.js CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install Test Dependency
        run: npm i -g -D jest
      - run: npm ci
      - run: npm test
      - run: echo Welcome to CSYE 6200!
        run: exit 1
      - run: echo This should not work!!

