name: Packer Build Machine Image

on: [push]

jobs:
    packer-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packer
        outputs:
          image_name:  # Define output variable (without -output)
          description: "Custom Machine Image Name"
          value: ${{ steps.custom-machine-image-name.outputs.image_name }}  # Reference step output
        name: Packer Build Machine Image
        steps:
            - name: Source Code Checkout
              uses: "actions/checkout@v3"

            - name: Authenticating with GCP Service Account
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

            - name: Packer Setup
              uses: hashicorp/setup-packer@main
              with:
                  version: "latest"

            - name: Packer Init
              run: "packer init $GITHUB_WORKSPACE/packer/."

            - name: Packer Validate
              run: 'packer validate -var "centos_project_id=${{ secrets.GCP_WEBAPP_PROJECT_ID }}" -var "centos_source_image_family=${{ secrets.GCP_WEBAPP_SOURCE_IMAGE_FAMILY }}" -var "centos_zone=${{ secrets.GCP_WEBAPP_ZONE }}" -var "centos_disable_default_service_account=${{ secrets.GCP_WEBAPP_DISABLE_DEFAULT_SA }}" -var "centos_region=${{ secrets.GCP_WEBAPP_REGION }}" -var "centos_machine_type=${{ secrets.GCP_WEBAPP_MACHINE_TYPE }}" -var "centos_image_name=${{ secrets.GCP_WEBAPP_IMAGE_NAME }}" -var "centos_ssh_username=${{ secrets.GCP_WEBAPP_SSH_USERNAME }}" $GITHUB_WORKSPACE/packer/. '

            - id: custom-machine-image-name
              name: Packer Build Machine Image
              run: |
                packer build -var "centos_project_id=${{ secrets.GCP_WEBAPP_PROJECT_ID }}" -var "centos_source_image_family=${{ secrets.GCP_WEBAPP_SOURCE_IMAGE_FAMILY }}" -var "centos_zone=${{ secrets.GCP_WEBAPP_ZONE }}" -var "centos_disable_default_service_account=${{ secrets.GCP_WEBAPP_DISABLE_DEFAULT_SA }}" -var "centos_region=${{ secrets.GCP_WEBAPP_REGION }}" -var "centos_machine_type=${{ secrets.GCP_WEBAPP_MACHINE_TYPE }}" -var "centos_image_name=${{ secrets.GCP_WEBAPP_IMAGE_NAME }}" -var "centos_ssh_username=${{ secrets.GCP_WEBAPP_SSH_USERNAME }}" $GITHUB_WORKSPACE/packer/. 2>&1 | tee $GITHUB_WORKSPACE/data.txt
                image_name=$(awk -F'project: ' '/project:/ && $2 {sub(/^[[:space:]]*/, "", $2); print substr($2, 1)}' $GITHUB_WORKSPACE/data.txt)
                echo "Image Name: $image_name"
                echo "::set-output name=image_name::$image_name"  # No longer needed

    create-new-instance-template:
      needs: packer-build
      runs-on: ubuntu-latest
      steps:
        - env:
            name: Create New Instance Template
            IMAGENAMEOUTPUT: ${{ needs.packer-build.outputs.image_name }}  # Access output variable
          run: |
            echo "Output from Packer Build: $IMAGENAMEOUTPUT"