name: Packer Validate

on: [pull_request]

jobs:
    fmt-check:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packer
        name: Packer Check Formatting
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Packer fmt
              run: packer fmt -check $GITHUB_WORKSPACE/packer/.

    validate:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packer
        name: Validate Packer Configuration
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Packer Init
              run: packer init $GITHUB_WORKSPACE/packer/.

            - name: Packer Validate
              run: 'packer validate -var "centos_project_id=${{ secrets.GCP_WEBAPP_PROJECT_ID }}" -var "centos_source_image_family=${{ secrets.GCP_WEBAPP_SOURCE_IMAGE_FAMILY }}" -var "centos_zone=${{ secrets.GCP_WEBAPP_ZONE }}" -var "centos_disable_default_service_account=${{ secrets.GCP_WEBAPP_DISABLE_DEFAULT_SA }}" -var "centos_region=${{ secrets.GCP_WEBAPP_REGION }}" -var "centos_machine_type=${{ secrets.GCP_WEBAPP_MACHINE_TYPE }}" -var "centos_image_name=${{ secrets.GCP_WEBAPP_IMAGE_NAME }}" -var "centos_ssh_username=${{ secrets.GCP_WEBAPP_SSH_USERNAME }}" $GITHUB_WORKSPACE/packer/. '
