name: Packer Build Machine Image

on: [push]

jobs:
    packer-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packer
        outputs:
          imageNameOutput: ${{ steps.step2.outputs.imageName }}
        name: Packer Build Machine Image
        steps:
            - name: Source Code Checkout
              uses: "actions/checkout@v3"

            - name: Authenticating with GCP Service Account
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

            - name: Packer Setup
              uses: hashicorp/setup-packer@main
              with:
                  version: "latest"

            - name: Packer Init
              run: "packer init $GITHUB_WORKSPACE/packer/."

            - name: Packer Validate
              run: 'packer validate -var "centos_project_id=${{ secrets.GCP_WEBAPP_PROJECT_ID }}" -var "centos_source_image_family=${{ secrets.GCP_WEBAPP_SOURCE_IMAGE_FAMILY }}" -var "centos_zone=${{ secrets.GCP_WEBAPP_ZONE }}" -var "centos_disable_default_service_account=${{ secrets.GCP_WEBAPP_DISABLE_DEFAULT_SA }}" -var "centos_region=${{ secrets.GCP_WEBAPP_REGION }}" -var "centos_machine_type=${{ secrets.GCP_WEBAPP_MACHINE_TYPE }}" -var "centos_image_name=${{ secrets.GCP_WEBAPP_IMAGE_NAME }}" -var "centos_ssh_username=${{ secrets.GCP_WEBAPP_SSH_USERNAME }}" $GITHUB_WORKSPACE/packer/. '

            - id: step2
              name: Packer Build Machine Image
              run: |
                packer build -var "centos_project_id=${{ secrets.GCP_WEBAPP_PROJECT_ID }}" -var "centos_source_image_family=${{ secrets.GCP_WEBAPP_SOURCE_IMAGE_FAMILY }}" -var "centos_zone=${{ secrets.GCP_WEBAPP_ZONE }}" -var "centos_disable_default_service_account=${{ secrets.GCP_WEBAPP_DISABLE_DEFAULT_SA }}" -var "centos_region=${{ secrets.GCP_WEBAPP_REGION }}" -var "centos_machine_type=${{ secrets.GCP_WEBAPP_MACHINE_TYPE }}" -var "centos_image_name=${{ secrets.GCP_WEBAPP_IMAGE_NAME }}" -var "centos_ssh_username=${{ secrets.GCP_WEBAPP_SSH_USERNAME }}" $GITHUB_WORKSPACE/packer/. 2>&1 | tee $GITHUB_WORKSPACE/data.txt
                output=$(awk -F'project: ' '/project:/ && $2 {sub(/^[[:space:]]*/, "", $2); print $2}' $GITHUB_WORKSPACE/data.txt)
                echo "$output"
                echo "imageName=$output" >> "$GITHUB_OUTPUT"
            - id: step1
              run: echo "imageName2=$output" >> "$GITHUB_OUTPUT"

    create-new-instance-template:
      needs: packer-build
      runs-on: ubuntu-latest
      steps:
        - name: Create New Instance Template
          env:
            IMAGENAMEOUTPUT: ${{needs.packer-build.outputs.imageNameOutput}}
          run: |
            echo "Output from Packer Build: $IMAGENAMEOUTPUT"